### ISSUE TITLE
Missing theme from sublime package installation

### ISSUE THREAD

**Issue by dtomlinson91** [poucotm/LikeGit#1]
Great addon for sublime, just discovered it from the package control.

Getting this error when installing from package control on Mac OS: 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/53234158/70102394-dae5f900-162f-11ea-818e-e0400565e57f.png">

Copying `Packages/LikeGit/theme/LikeGit.tmTheme.templ` to `Sublime Text 3/Packages/User/LikeGit/LikeGit.tmTheme` and setting `+x` permissions gets rid of the error:

<img width="629" alt="image" src="https://user-images.githubusercontent.com/53234158/70103070-f2be7c80-1631-11ea-9d85-7226f87f8d2b.png">

but the color scheme is off.

**Comment by poucotm** [comment]
I updated the codes. Could you try with v0.5.2 ?

**Comment by dtomlinson91** [comment]
I removed and reinstalled it using the Sublime package control.

It's installing fine :) But I'm still seeing this weird colour scheme: 

<img width="645" alt="image" src="https://user-images.githubusercontent.com/53234158/70186017-d9c1d400-16e2-11ea-934b-b17e6c316d7a.png">

Am I doing anything wrong? I can provide more info/logs if you need it.

**Comment by poucotm** [comment]
It looks there is some problem of applying coloring region. But I don't know the reason. Unfortunately, I cannot test for Mac OS. Is that possible to test with other OS?

**Comment by dtomlinson91** [comment]
I can test on Windows and Linux tomorrow. I'll update this ticket with the results.

Thanks again for the addon, I really like it.

**Comment by barnumbirr** [comment]
Ran into the same issue on Windows 10 (ST3.2.2, Likegit 0.5.2)

**Comment by poucotm** [comment]
@dtomlinson91 , @barnumbirr , What are your git versions ?
Would you check `git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"` in git bash ?

![image](https://user-images.githubusercontent.com/19210389/70381804-54fde100-1994-11ea-8a85-f1c6dcb1b112.png)

**Comment by barnumbirr** [comment]
Hello there,

so here's the output you asked for:

```bash
$ git --version 
git version 2.22.0.windows.1 
```
and output of `git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"` looks fine:

![Capture](https://user-images.githubusercontent.com/2029239/70381880-5e665980-1952-11ea-848b-23dee72b5c5e.PNG)

Thanks for looking into this.

Cheers.

**Comment by poucotm** [comment]
I added 'debug' option in settings to find a cause (v0.5.3). After adding "debug" : true in LikeGit setting (Preferences > Package settings > LikeGit > Settings), please, show me the result in Console (Ctrl+`).

e.g)
1. text in the Console
* <tab>[31mf868b1d<tab>[32m (HEAD, master)[0m asdfasdf
* <tab>[31me8eb8b4<tab>[32m[0m asdfasdf

2. capture screen

![image](https://user-images.githubusercontent.com/19210389/70382792-eb3a0300-19a4-11ea-82e5-ea0aa374ef1c.png)

**Comment by barnumbirr** [comment]
This is weird: when `debug` is enabled, everything works as expected.

![Capture](https://user-images.githubusercontent.com/2029239/70387631-a6fc3200-19a7-11ea-8543-a4ac69041d9c.PNG)

```bash
[...]
[36m|[m[1;31m\[m [1;31m\[m [32m\[m [1;34m\[m [34m\[m [1;36m\[m [31m\[m  
[36m|[m * [1;31m\[m [32m\[m [1;34m\[m [34m\[m [1;36m\[m [31m\[m   <tab>[31m1dec2ab<tab>[32m[0m Merge branch 'master' into patch-1
[36m|[m [1;32m|[m[36m\[m [1;31m\[m [32m\[m [1;34m\[m [34m\[m [1;36m\[m [31m\[m  
[36m|[m [1;32m|[m[36m/[m [1;31m/[m [32m/[m [1;34m/[m [34m/[m [1;36m/[m [31m/[m  
[36m|[m[36m/[m[1;32m|[m [1;31m|[m [32m|[m [1;34m|[m [34m|[m [1;36m|[m [31m|[m   
```
If I turn `debug` off, output color is "broken" again: 

![Capture2](https://user-images.githubusercontent.com/2029239/70387647-e6c31980-19a7-11ea-832e-842aabd8c959.PNG)

Cheers.

**Comment by poucotm** [comment]
?? It is so weird. It looks like there is some difference btw. your and my system to handle a tab. I don't know why, but temporal workaround is to use spaces instead of a tab. I updated the codes v0.5.4 for it.

**Comment by barnumbirr** [comment]
So for some weird reason v0.5.4 fixes the issue for me, even without `debug` being set to `true`. @dtomlinson91 can you try on your side and see if you get the same result.

In the meantime I'll check to see if using spaces instead of tabs didn't break the plugin on Linux/OSX.

Thanks for the fix @poucotm, much appreciated. This plugin is 🔥

**Update:** tried on OSX as promised: v0.5.4 works as expected even without `debug` being set to `true`.
